apiVersion: "v3.1.0"
kind: "DataContract"
id: "orders_data_mart"
name: "Orders Data Mart"
version: "1.0.0"
status: "proposed"
description:
  purpose: "Orders data mart containing facts and dimensions for order analysis."
team:
  name: "sales-team"
schema:
- name: "fact_orders"
  physicalType: "table"
  businessName: "Fact Orders"
  description: "Fact table containing order information."
  properties:
  - name: "ORDER_ID"
    logicalType: "string"
    description: "Unique identifier for each order."
    businessName: "Order ID"
    primaryKey: true
  - name: "CUSTOMER_ID"
    logicalType: "string"
    description: "Unique identifier for the customer who placed the order."
    businessName: "Customer ID"
    required: true
    relationships:
    - to: "dim_customers.CUSTOMER_ID"
      type: "foreignKey"
  - name: "ORDER_DATE"
    logicalType: "timestamp"
    description: "Date the order was created."
    businessName: "Order Date"
    required: true
  - name: "ORDER_TOTAL"
    logicalType: "number"
    physicalType: "DECIMAL(38,2)"
    description: "Total amount for the order."
    businessName: "Order Total"
    required: true
  - name: "SHIPPING_METHOD_ID"
    logicalType: "string"
    description: "Identifier for the shipping method."
    businessName: "Shipping Method ID"
    required: true
    relationships:
    - to: "dim_shipping_methods.SHIPPING_METHOD_ID"
      type: "foreignKey"
  - name: "PROMOTION_ID"
    logicalType: "string"
    description: "Applied promotion for the order."
    businessName: "Promotion ID"
    relationships:
    - to: "dim_promotions.PROMOTION_ID"
      type: "foreignKey"
  - name: "STATUS_ID"
    logicalType: "string"
    description: "Current status of the order."
    businessName: "Status ID"
    required: true
    relationships:
    - to: "dim_order_status.STATUS_ID"
      type: "foreignKey"
  - name: "REGION_ID"
    logicalType: "string"
    description: "Identifier for the region of the order."
    businessName: "Region ID"
    relationships:
    - to: "dim_regions.REGION_ID"
      type: "foreignKey"
- name: "fact_line_items"
  physicalType: "table"
  businessName: "Fact Line Items"
  description: "Fact table containing line item details for each order."
  properties:
  - name: "LINE_ITEM_ID"
    logicalType: "string"
    description: "Unique identifier for each line item."
    businessName: "Line Item ID"
    primaryKey: true
  - name: "ORDER_ID"
    logicalType: "string"
    description: "Identifier of the associated order."
    businessName: "Order ID"
    required: true
    relationships:
    - to: "fact_orders.ORDER_ID"
      type: "foreignKey"
  - name: "ARTICLE_SKU"
    logicalType: "string"
    description: "Stock-keeping unit for the item."
    businessName: "Article SKU"
    required: true
    relationships:
    - to: "dim_products.PRODUCT_ID"
      type: "foreignKey"
  - name: "QUANTITY"
    logicalType: "integer"
    description: "Quantity of the item ordered."
    businessName: "Quantity"
    required: true
  - name: "LINE_TOTAL"
    logicalType: "number"
    physicalType: "DECIMAL(12,2)"
    description: "Total amount for the line item."
    businessName: "Line Total"
    required: true
- name: "fact_shipments"
  physicalType: "table"
  businessName: "Fact Shipments"
  description: "Fact table containing shipment details for orders."
  properties:
  - name: "SHIPMENT_ID"
    logicalType: "string"
    description: "Unique identifier for each shipment."
    businessName: "Shipment ID"
    primaryKey: true
  - name: "ORDER_ID"
    logicalType: "string"
    description: "Identifier of the associated order."
    businessName: "Order ID"
    required: true
    relationships:
    - to: "fact_orders.ORDER_ID"
      type: "foreignKey"
  - name: "SHIPPING_METHOD_ID"
    logicalType: "string"
    description: "Identifier for the shipping method."
    businessName: "Shipping Method ID"
    required: true
    relationships:
    - to: "dim_shipping_methods.SHIPPING_METHOD_ID"
      type: "foreignKey"
  - name: "SHIPMENT_DATE"
    logicalType: "timestamp"
    description: "Date the shipment was dispatched."
    businessName: "Shipment Date"
    required: true
  - name: "REGION_ID"
    logicalType: "string"
    description: "Identifier for the destination region of the shipment."
    businessName: "Region ID"
    required: true
    relationships:
    - to: "dim_regions.REGION_ID"
      type: "foreignKey"
  - name: "CARRIER_ID"
    logicalType: "string"
    description: "Identifier for the carrier responsible for the shipment."
    businessName: "Carrier ID"
    required: true
    relationships:
    - to: "dim_carriers.CARRIER_ID"
      type: "foreignKey"
- name: "dim_customers"
  physicalType: "table"
  businessName: "Dimension Customers"
  description: "Dimension table containing customer information."
  properties:
  - name: "CUSTOMER_ID"
    logicalType: "string"
    description: "Unique identifier for each customer."
    businessName: "Customer ID"
    primaryKey: true
  - name: "CUSTOMER_NAME"
    logicalType: "string"
    description: "Full name of the customer."
    businessName: "Customer Name"
    required: true
  - name: "EMAIL"
    logicalType: "string"
    description: "Customer's email address."
    businessName: "Email"
    tags:
    - "pii:true"
  - name: "PHONE_NUMBER"
    logicalType: "string"
    description: "Customer's phone number."
    businessName: "Phone Number"
    tags:
    - "pii:true"
- name: "dim_products"
  physicalType: "table"
  businessName: "Dimension Products"
  description: "Dimension table containing product information."
  properties:
  - name: "PRODUCT_ID"
    logicalType: "string"
    description: "Unique identifier for each product."
    businessName: "Product ID"
    primaryKey: true
  - name: "PRODUCT_NAME"
    logicalType: "string"
    description: "Name of the product."
    businessName: "Product Name"
  - name: "CATEGORY"
    logicalType: "string"
    description: "Product category."
    businessName: "Category"
  - name: "PRICE"
    logicalType: "number"
    physicalType: "DECIMAL(12,2)"
    description: "Unit price of the product."
    businessName: "Price"
    required: true
- name: "dim_shipping_methods"
  physicalType: "table"
  businessName: "Dimension Shipping Methods"
  description: "Dimension table containing shipping method details."
  properties:
  - name: "SHIPPING_METHOD_ID"
    logicalType: "string"
    description: "Unique identifier for each shipping method."
    businessName: "Shipping Method ID"
    primaryKey: true
  - name: "METHOD_NAME"
    logicalType: "string"
    description: "Name of the shipping method (e.g., Standard, Express)."
    businessName: "Method Name"
    required: true
- name: "dim_carriers"
  physicalType: "table"
  businessName: "Dimension Carriers"
  description: "Dimension table containing carrier details."
  properties:
  - name: "CARRIER_ID"
    logicalType: "string"
    description: "Unique identifier for each carrier."
    businessName: "Carrier ID"
    primaryKey: true
  - name: "CARRIER_NAME"
    logicalType: "string"
    description: "Name of the carrier company."
    businessName: "Carrier Name"
    required: true
- name: "dim_regions"
  physicalType: "table"
  businessName: "Dimension Regions"
  description: "Dimension table containing regional information."
  properties:
  - name: "REGION_ID"
    logicalType: "string"
    description: "Unique identifier for each region."
    businessName: "Region ID"
    primaryKey: true
  - name: "REGION_NAME"
    logicalType: "string"
    description: "Name of the region."
    businessName: "Region Name"
- name: "dim_promotions"
  physicalType: "table"
  businessName: "Dimension Promotions"
  description: "Dimension table containing promotion details."
  properties:
  - name: "PROMOTION_ID"
    logicalType: "string"
    description: "Unique identifier for each promotion."
    businessName: "Promotion ID"
    primaryKey: true
  - name: "PROMOTION_NAME"
    logicalType: "string"
    description: "Name of the promotion."
    businessName: "Promotion Name"
  - name: "DISCOUNT_PERCENTAGE"
    logicalType: "number"
    physicalType: "DECIMAL(5,2)"
    description: "Percentage discount offered by the promotion."
    businessName: "Discount Percentage"
- name: "dim_order_status"
  physicalType: "table"
  businessName: "Dimension Order Status"
  description: "Dimension table containing order status information."
  properties:
  - name: "STATUS_ID"
    logicalType: "string"
    description: "Unique identifier for each status."
    businessName: "Status ID"
    primaryKey: true
  - name: "STATUS_NAME"
    logicalType: "string"
    description: "Name of the status."
    businessName: "Status Name"
