apiVersion: "v3.1.0"
kind: "DataContract"
id: "s3_customers_history_pii_v1"
name: "Customers History"
version: "1.0.0"
status: "active"
tags:
  - "popular"
description:
  purpose: "All customer states, updated on every modifying event. PII included."
  usage: "Max. 10x queries per day"
  limitations: "Not suitable for real-time use cases"
team:
  name: "sales-team"
  members:
    - username: "scarlett.layton@demo4OH8794gsA1S7tFCbEFHxy.datamesh-manager.com"
      name: "Scarlett Layton"
      role: "contact"
price:
  priceAmount: 1000
  priceCurrency: "USD"
  priceUnit: "month"
customProperties:
  - property: "noticePeriod"
    value: "P3M"
servers:
  - server: "s3-customers-history-pii"
    type: "s3"
    location: "s3://customers-history-pii-v1/"
    format: "parquet"
schema:
  - name: "customers"
    physicalType: "table"
    businessName: "Customers"
    description: "Retrieves and transforms customer data"
    properties:
      - name: "customer_id"
        logicalType: "string"
        required: true
        unique: true
        authoritativeDefinitions:
          - type: "definition"
            url: "http://localhost:8888/demo930914837096/definitions/sales/customer_id"
      - name: "name"
        logicalType: "string"
        description: "Full name of the customer"
        tags:
          - "pii:true"
      - name: "email"
        logicalType: "string"
        authoritativeDefinitions:
          - type: "definition"
            url: "http://localhost:8888/demo930914837096/definitions/sales/customer_email"
      - name: "phone"
        logicalType: "string"
        description: "Phone number of the customer"
        tags:
          - "pii:true"
      - name: "address"
        logicalType: "string"
        description: "Address of the customer"
        tags:
          - "pii:true"
      - name: "created_at"
        logicalType: "timestamp"
        description: "Timestamp indicating when the customer record was created"
        required: true
tenant: "tenant4"
