apiVersion: "v3.1.0"
kind: "DataContract"
id: "snowflake_orders_pii_v2"
name: "Orders v2"
version: "2.0.0"
status: "active"
tags:
- "popular"
description:
  purpose: "All order-created events, with PII.2"
  usage: "Max. 10x queries per day"
  limitations: "Not suitable for real-time use cases"
  authoritativeDefinitions:
  - type: "policy"
    url: "http://localhost:8888/demo930914837096/policies/gdpr"
    description: "GDPR"
  - type: "policy"
    url: "http://localhost:8888/demo930914837096/policies/data-retention"
    description: "Data Retention Policy"
team:
  name: "sales-team"
  members:
  - username: "scarlett.layton@demo4OH8794gsA1S7tFCbEFHxy.datamesh-manager.com"
    name: "Scarlett Layton"
    role: "contact"
price:
  priceAmount: 1000
  priceCurrency: "USD"
  priceUnit: "month"
customProperties:
- property: "noticePeriod"
  value: "P3M"
roles:
- role: "orders.analyst.eu.read"
  access: "read"
  description: "Read-only access for for all orders in EU"
- role: "orders.analyst.us.read"
  access: "read"
  description: "Read-only access for for all orders in US"
- role: "orders.exploration.eu.read"
  access: "read"
  description: "Time limited role for exploration or proof-of-concept work"
- role: "orders.exploration.us.read"
  access: "read"
  description: "Time limited role for exploration or proof-of-concept work"
servers:
- server: "snowflake"
  type: "snowflake"
  account: "lmtrwxs-xn14859"
  database: "ORDER_DB"
  schema: "ORDERS_PII_V2"
slaProperties:
- property: "availability"
  value: "99.9"
  unit: "%"
  description: "The server is available during support hours"
- property: "retention"
  value: "P1Y"
  description: "Data is retained for one year"
- property: "freshness"
  value: "25h"
  description: "The age of the youngest row in a table."
- property: "frequency"
  value: "daily"
  description: "Data is delivered once a day"
schema:
- name: "orders"
  physicalType: "table"
  businessName: "Orders"
  description: "Table containing order information with PII."
  properties:
  - name: "ORDER_ID"
    logicalType: "string"
    required: true
    primaryKey: true
    tags:
    - "business-key"
    authoritativeDefinitions:
    - type: "definition"
      url: "http://localhost:8888/demo930914837096/definitions/sales/order_id"
  - name: "PREVIOUS_ORDER_ID"
    logicalType: "string"
    description: "If this order is a follow up as customer service had to cancel the previous order, the order id of the previous order is put in there."
    businessName: "Previous Order ID"
    relationships:
    - to: "orders.ORDER_ID"
      type: "foreignKey"
    authoritativeDefinitions:
    - type: "definition"
      url: "http://localhost:8888/demo930914837096/definitions/sales/order_id"
  - name: "CUSTOMER_ID"
    logicalType: "string"
    required: true
    authoritativeDefinitions:
    - type: "definition"
      url: "http://localhost:8888/demo930914837096/definitions/sales/customer_id"
  - name: "EMAIL"
    logicalType: "string"
    authoritativeDefinitions:
    - type: "definition"
      url: "http://localhost:8888/demo930914837096/definitions/sales/customer_email"
  - name: "PHONE_NUMBER"
    logicalType: "string"
    physicalType: "text"
    description: "phone number of the customer"
    businessName: "Phone Number"
    tags:
    - "pii:true"
  - name: "INVOICE_ADDRESS"
    logicalType: "object"
    description: "The address that is put in the invoice."
    properties:
    - name: "ADDRESS_LINE"
      logicalType: "string"
      physicalType: "text"
      description: "Street name and number"
      businessName: "Street"
    - name: "CITY_LINE"
      logicalType: "string"
      physicalType: "text"
      description: "City name and ZIP Code"
      businessName: "City and ZIP Code"
  - name: "ORDER_DATE"
    logicalType: "timestamp"
    description: "Date of the order"
    businessName: "Order Date"
    required: true
  - name: "ORDER_TOTAL"
    logicalType: "number"
    physicalType: "number"
    description: "Total amount of the order"
    businessName: "Order Total"
    required: true
- name: "line_items"
  physicalType: "table"
  businessName: "Line Items"
  description: "Table containing line items of an order."
  properties:
  - name: "LINE_ITEM_ID"
    logicalType: "string"
    description: "The unique identifier of the line item. A simple UUID is generated."
    primaryKey: true
    logicalTypeOptions:
      format: "uuid"
  - name: "ORDER_ID"
    logicalType: "string"
    required: true
    relationships:
    - to: "orders.ORDER_ID"
      type: "foreignKey"
    authoritativeDefinitions:
    - type: "definition"
      url: "http://localhost:8888/demo930914837096/definitions/sales/order_id"
  - name: "ARTICLE_SKU"
    logicalType: "string"
    required: true
    authoritativeDefinitions:
    - type: "definition"
      url: "http://localhost:8888/demo930914837096/definitions/fulfillment/sku"
